add python script to create a markdown report for clang-tidy warnings. Filter out generated third-party headers

diff --git a/.github/workflows/clang-tidy.yaml b/.github/workflows/clang-tidy.yaml
--- a/.github/workflows/clang-tidy.yaml
+++ b/.github/workflows/clang-tidy.yaml
@@ -67,37 +67,63 @@ jobs:
           CXX: clang++
         run: |
           echo "Running cmake..."
-          cmake -B build-${{ matrix.cmake_options }} \
+          cmake
+            -S . \
+            -B build-${{ matrix.cmake_options }} \
             -C ./test_common/cmake/${{ matrix.cmake_options }}.cmake \
             -DCMAKE_CXX_STANDARD=14 \
             -DWITH_STL=CXX14 \
             -DWITH_OPENTRACING=OFF \
             -DCMAKE_CXX_FLAGS="-Wno-deprecated-declarations" \
             -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
-            -DCMAKE_CXX_CLANG_TIDY="clang-tidy;--header-filter=.*;--exclude-header-filter=.*internal/absl/.*;--quiet" 
+            -DCMAKE_CXX_CLANG_TIDY="clang-tidy;--header-filter=.*/opentelemetry-cpp/.*;--exclude-header-filter=.*(internal/absl|third_party|third-party)/.*;--quiet"
 
-      - name: Run clang-tidy
+      - name: Run clang-tidy and Build
+        id: build
         run: |
-          cmake --build build-${{ matrix.cmake_options }} -- -j$(nproc) 2>&1 | tee clang-tidy-${{ matrix.cmake_options }}.log
+          BUILD_LOG=clang-tidy-${{ matrix.cmake_options }}.log
+          set -o pipefail
+          cmake --build build-${{ matrix.cmake_options }} -- -j$(nproc) 2>&1 | tee $BUILD_LOG
+          echo "build_log=$BUILD_LOG" >> "$GITHUB_OUTPUT"
 
-      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
+      - name: Analyze clang-tidy build log
+        id: analyze
+        run: |
+          SCRIPT_OUTPUT=$(python3 ./ci/create_clang_tidy_report.py \
+            --job_name ${{ matrix.cmake_options }} \
+            --build_log clang-tidy-${{ matrix.cmake_options }}.log \
+            --output ./clang_tidy_report-${{ matrix.cmake_options }}.md)
+          export $SCRIPT_OUTPUT
+          echo "Found $TOTAL_WARNINGS unique warnings"
+          echo "clang-tidy report generated at $REPORT_PATH"
+          echo "warning_count=$TOTAL_WARNINGS" >> "$GITHUB_OUTPUT"
+          echo "report_path=$REPORT_PATH" >> "$GITHUB_OUTPUT"
+          cat $REPORT_PATH >> $GITHUB_STEP_SUMMARY
+
+      - name: Upload build log
+        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
         with:
           name: Logs-clang-tidy-${{ matrix.cmake_options }}
-          path: ./clang-tidy-${{ matrix.cmake_options }}.log
+          path: ${{ steps.build.outputs.build_log }}
 
-      - name: Count warnings
+      - name: Upload warning report
+        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
+        with:
+          name: Report-clang-tidy-${{ matrix.cmake_options }}
+          path: ${{ steps.analyze.outputs.report_path }}
+
+      - name: Check Warning Limits
         run: |
-          COUNT=$(grep -c "warning:" clang-tidy-${{ matrix.cmake_options }}.log)
-          echo "clang-tidy reported ${COUNT} warning(s) with cmake options preset '${{ matrix.cmake_options }}'"
+          readonly COUNT="${{ steps.analyze.outputs.warning_count }}"
+          readonly LIMIT="${{ matrix.warning_limit }}"
 
-          readonly WARNING_LIMIT=${{ matrix.warning_limit }}
+          echo "clang-tidy reported ${COUNT} unique warning(s) with preset '${{ matrix.cmake_options }}'"
+          echo "Limit is ${LIMIT}"
 
-          # FAIL the build if COUNT > WARNING_LIMIT
-          if [ $COUNT -gt $WARNING_LIMIT ] ; then
-            echo "clang-tidy reported ${COUNT} warning(s) exceeding the existing warning limit of ${WARNING_LIMIT} with cmake options preset '${{ matrix.cmake_options }}'"
+          if [ "$COUNT" -gt "$LIMIT" ]; then
+            echo "::error::clang-tidy reported ${COUNT} warning(s) exceeding the limit of ${LIMIT}"
             exit 1
-          # WARN in annotations if COUNT > 0
-          elif [ $COUNT -gt 0 ] ; then
-            echo "::warning::clang-tidy reported ${COUNT} warning(s) with cmake options preset '${{ matrix.cmake_options }}'"
+          elif [ "$COUNT" -gt 0 ]; then
+            echo "::warning::clang-tidy reported ${COUNT} warning(s) within the limit of ${LIMIT}"
           fi
 
